config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new, :create, :destroy]

  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :years, shallow: true, except: [:update, :edit, :destroy, :show] do
    resources :months, shallow: true, only: [:index]
    resources :payments, only: [:index]
  end

  resources :months, shallow: true, only: [:show, :index] do
    resources :payments, except: [:edit, :update, :destroy, :show]
  end

end

app/models/month.rb
class Month < ActiveRecord::Base
  has_many :payments, inverse_of: :month
  has_and_belongs_to_many :years
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :month, inverse_of: :payments, required: true

  scope :debit_behind_year, ->(y) { where(year: y) }
  default_scope -> { order('month_id ASC') }

  before_create :set_debit

  validates :payment, presence: true
  validates :payment, numericality: { greater_than_or_equal_to: 0.01 }
  validates :other_payment,
            numericality: { greater_than_or_equal_to: 0 },
            unless: proc { |a| a.other_payment.blank? }

  private

  def set_debit
    self.debit = 7500 - payment - other_payment
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_and_belongs_to_many :months

  validates :value_year, presence: true, uniqueness: true,
                         numericality: { only_integer: true,
                                         greater_than: 2000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    # flash[:warning] = 'Вы не авторизованы, для этого действия'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  def index
    @months = Month.all
    session[:current_year_id] = params[:year_id]
    authorize @months
  end

  def show
    @month = Month.find(params[:id])
    @payment = @month.payments.order(:id).last
    authorize @month
    session[:current_year_id] = nil
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @payments = Payment.debit_behind_year(params[:year_id])
    @sum_debit_behind_year = @payments.sum(:debit)
  end

  def new
    @month = Month.find(params[:month_id])
    @payment = @month.payments.build
  end

  def create
    @month = Month.find(params[:month_id])
    @payment = @month.payments.build(payments_params)
    authorize @payment
    @payment.year = session[:current_year_id]
    if @payment.save
      redirect_to @month
    else
      render 'new'
    end
  end

  private

  def payments_params
    params.require(:payment)
          .permit(:payment, :other_payment, :description, :month_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash[:alert] = 'Неправильный логин или пароль'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to root_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  def index
    @years = Year.order(:value_year)
    @debit = Payment.sum(:debit)
  end

  def new
    @year = Year.new
    authorize @year
  end

  def create
    @year = Year.create(year_params)
    if @year.save
      redirect_to years_path
    else
      render 'new'
    end
  end

  private

  def year_params
    params.require(:year).permit(:value_year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/years_helper.rb
module YearsHelper
  def add_link_to_for_admin(value)
    if policy(@years).new?
      link_to value, yield, class: 'btn btn-success'
    else
      value
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://google.com/">Google</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
    <%= link_to 'Коммунальные платежи', years_path, id: 'logo' %>
      <nav>
      <ul class="nav pull-right">
        <li><%= link_to 'На главную', years_path %></li>

        <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                Аккаунт <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Профиль', current_user %></li>
                <li><%= link_to 'Редактирование', edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Выход', signout_path, method: 'delete' %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to 'Вход', signin_path %></li>
        <% end %>
      </ul>
      </nav>
    </div>
  </div>
</header>



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Коммунальные платежи</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/months/index.html.erb
<div class="row">
  <div class="col-lg-6 col-xs-6 text-center">
    <h3><strong>Создать новый платеж за:</strong></h3>
  </div>

  <div class="col-lg- col-xs-6">
    <dl id="size-month">
      <% @months.each do |month| %>
          <dt><%= link_to month.name_month, new_month_payment_path(month.id) %></dt>
      <% end %>
    </dl>
  </div>
</div>

<div class="row">
  <div class="col-lg-6 col-xs-6 center">
    <%= button_to 'Назад', years_path, method: :get, class: 'btn btn-success' %>
  </div>
</div>

app/views/months/show.html.erb
<div class="row center margin-bottom">
  <div class="col-lg-12 col-xs-12">
    <h4><strong><%= @month.name_month %></strong></h4>
  </div>
</div>

<div class="row center size-and-margin-bottom">
  <div class="col-lg-6 col-xs-6">
    <div>Сумма:</div>
  </div>
  <div class="col-lg-6 col-xs-6">
    <div><%= @payment.payment %></div>
  </div>
</div>

<div class="row center size-and-margin-bottom">
  <div class="col-lg-6 col-xs-6">
    <div>Прочие расходы:</div>
  </div>
  <div class="col-lg-6 col-xs-6">
    <div><%= @payment.other_payment %></div>
  </div>
</div>

<div class="row center size-and-margin-bottom">
  <div class="col-lg-6 col-xs-6">
    <div>Описание:</div>
  </div>
  <div class="col-lg-6 col-xs-6">
    <div><%= @payment.description %></div>
  </div>
</div>

<div class="row center">
  <div class="col-lg-6 col-xs-6">
    <%= link_to 'Выбор года', years_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/payments/_form.html.erb
<%= form_for [@month, @payment], action: new_month_payment_path do |f| %>
  <div class="center"><%= render 'shared/error_messages', obj: @payment %></div>

    <div class="row center">
      <div class="col-lg-6 col-xs-6 text-right">
        <%= f.label 'Сумма платежа' %>
      </div>
      <div class="col-lg-6 col-xs-6 text-left">
        <%= f.text_field :payment %>
      </div>
    </div>

    <div class="row center">
      <div class="col-lg-6 col-xs-6 text-right">
        <%= f.label 'Затраты на ремонт' %>
      </div>
      <div class="col-lg-6 col-xs-6 text-left">
        <%= f.text_field :other_payment %>
      </div>
    </div>

    <div class="row center">
      <div class="col-lg-6 col-xs-6 text-right">
        <%= f.label 'Комментарий' %>
      </div>
      <div class="col-lg-6 col-xs-6 text-left">
        <%= f.text_field :description %>
      </div>
    </div>

    <div class="row center">
      <div class="col-lg-12 col-xs-12"><%= f.submit 'Добавить платеж', class: 'btn btn-success' %></div>
    </div>

<% end %>


app/views/payments/create.js.erb
//$('table.button').html("<#%= escape_javascript render '@month' %>");

app/views/payments/index.html.erb
<div class="row center size-and-margin-bottom">
  <div class="col-lg-2 col-xs-2">Сумма платежа</div>
  <div class="col-lg-2 col-xs-2">Сумма из долга</div>
  <div class="col-lg-4 col-xs-4">Описание</div>
  <div class="col-lg-2 col-xs-2">Долг</div>
  <div class="col-lg-2 col-xs-2">Месяц</div>
</div>

<% @payments.each do |payment| %>
    <div class="row center index-pay">
      <div class="col-lg-2 col-xs-2"><%= payment.payment %></div>
      <div class="col-lg-2 col-xs-2"><%= payment.other_payment %></div>
      <div class="col-lg-4 col-xs-4 description"><%= payment.description %></div>
      <div class="col-lg-2 col-xs-2"><%= payment.debit %></div>
      <div class="col-lg-2 col-xs-2"><%= payment.month.name_month %></div>
    </div>
<% end %>

<div class="row center" style="margin-bottom: 10px;">
  <div class="col-lg-2 col-xs-2"><strong>Сумма:</strong></div>
  <div class="col-lg-6 col-lg-offset-4 col-xs-6 col-xs-offset-4"><%= @sum_debit_behind_year %></div>
</div>

<div class="row center">
  <div class="col-lg-2 col-xs-2">
    <%= button_to 'На главную', years_path, method: :get, class: 'btn btn-success' %>
  </div>
  <div class="col-lg-10 col-xs-10"></div>
</div>

app/views/payments/new.html.erb
<div class="row center">
  <div class="col-lg-12 col-xs-12"><h3><strong>Новый платеж</strong></h3></div>
</div>

<%= render 'form' %>

<div>
  <span id="submitForm">fgf</span>
</div>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      У Вас имеется <%= pluralize(obj.errors.count, 'ошибка', 'ошибки') %>.
    </div>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', obj: @user %>
  <tr>
    <td><%= f.label :name, 'Имя' %></td>
    <td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <td><%= f.label :email %></td>
    <td><%= f.text_field :email %></td>
  </tr>
  <tr>
    <td><%= f.label :password, 'Пароль' %></td>
    <td><%= f.password_field :password %></td>
  </tr>
  <tr>
    <td><%= f.label :password_confirmation, 'Подтверждение пароля' %></td>
    <td><%= f.password_field :password_confirmation %></td>
  </tr>
  <tr>
    <td><%= f.submit 'Сохранить изменения', class: 'btn btn-large btn-primary' %></td>
  </tr>
<% end %>

app/views/users/edit.html.erb
<h1>Обновление вашего профиля</h1>

<div class="row center-bloc" id="margin_form">
  <table id="margin-form">
    <%= render 'form' %>
  </table>
</div>

app/views/users/show.html.erb
<div class="row">
  <h1><%= @user.name %></h1>
  <h2><%= @user.email %></h2>
</div>

app/views/years/_form.html.erb
<%= form_for @year, url: years_path, html: {role: 'form', class: 'form-inline'} do |f| %>
  <%= render 'shared/error_messages', obj: @year %>
  <div class="col-lg-6 col-xs-6 text-right" style="padding-top: 5px;">
    <%= f.text_field :value_year %>
  </div>
  <div class="col-lg-6 col-xs-6 text-left">
    <%= f.submit 'Добавить год', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/years/index.html.erb
<div class="row margin-bottom">
  <div class="col-lg-12 col-xs-12 center"><h3><strong>Выберите год:</strong></h3></div>
</div>

<% @years.each do |year| %>
  <div class="row margin-bottom">
    <div class="col-lg-6 col-xs-6 center" id="size-year">
      <%= link_to year.value_year, year_months_path(year.value_year) %>
    </div>
    <div class="col-lg-6 col-xs-6 center">
      <%= button_to 'Показать платежи за год', year_payments_path(year.value_year),
                                        method: :get, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

<div class="row margin-bottom">
  <div class="col-lg-6 col-xs-6 center">
    <%= add_link_to_for_admin('Добавить год'){new_year_path} %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6 col-xs-6 text-center">
    <h4><strong>Общая сумма долга:</strong></h4>
  </div>
  <div class="col-lg-6 col-xs-6 text-center">
    <h4><strong><%= @debit %></strong></h4>
  </div>
</div>

app/views/years/new.html.erb
<div class="row center margin-bottom">
  <div class="col-lg-12 col-xs-12">
    <h3><strong>Запишите год:</strong></h3>
  </div>
</div>

<div class="row center margin-bottom">
  <%= render 'form' %>
</div>

<div class="row center">
  <%= button_to 'Назад', years_path, method: :get, class: 'btn btn-success' %>
</div>